services:
  - type: web
    name: embedbase-render
    env: python
    plan: free
    buildCommand: "pip install -R requirements.txt"
    startCommand: "python3 main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.0
      - key: OPENAI_API_KEY
        sync: false
