services:
  - type: web
    name: embedbase-render
    env: python
    plan: free
    startCommand: "python3 main.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: OPENAI_API_KEY
        sync: false
